### PR TITLE
build(cli) oclif packaging for standalone distribution 

### PR DESCRIPTION
**Pull request by akollegger**
### Please check if the PR fulfills these requirements
- [x] The commit message follows our [guidelines](https://github.com/neo4j-devtools/relate/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?

Build improvement for @relate/cli to create standalone distributions which include a nodejs runtime.

### What is the current behavior?

@relate/cli is an npm package which requires nodejs.

### What is the new behavior?

Nodejs is now packaged along with the cli.

### Does this PR introduce a breaking change?

No changes expected to the functions of the cli. However, there is now the possibility that more than one @relate/cli is installed on the system (packaged with Desktop; installed with npm; installed as standalone cli).

### CODE REVIEW

**Comment by huboneo** [comment]
Just realised that we call `npm install` when adding extensions, so we need to make sure NPM is available in PATH

**Comment by akollegger** [comment]
@huboneo WDYT about switching to a library instead, like https://github.com/npm/libnpm ?

**Comment by huboneo** [comment]
In general I'm against using anything non-standard. How can we guarantee that said library keeps up with NPM? Is there an official recommendation from oclif?

**Comment by huboneo** [comment]
But libnpm does look like a good candidate should we not be able to use npm directly

**Pull request closed without merging**
