### PR TITLE
Add plugin sources list

### PR DESCRIPTION
**Pull request by nglgzz**
### Please check if the PR fulfills these requirements
- [x] The commit message follows our [guidelines](https://github.com/neo4j-devtools/relate/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?
Adds a file containing the official plugin sources for Relate.

### What is the current behavior?
-

### What is the new behavior?
-

### Does this PR introduce a breaking change?
No

### Other information:
-

### CODE REVIEW

**Comment by huboneo** [comment]
Why a file and not an endpoint?

**Comment by nglgzz** [comment]
Where would we have the endpoint?

I was thinking to use a file because:
- We can just get it from https://raw.githubusercontent.com/neo4j-devtools/relate/master/plugins.json once this is merged.
- It's simple enough to update, just create a PR and when it's merged all versions of relate will be able to pull the updated plugin sources.
- This is also how it's currently implemented for both the plugin sources file that the neo4j docker image is using and versions files that plugins host.

Is there anything I'm missing?

**Comment by huboneo** [comment]
yeah sure makes sense, just check github terms on using their repos for prod purposes. Any rate limits?

**Comment by nglgzz** [comment]
Maybe I should have also added in the description that another PR will follow this, to change the `NEO4J_PLUGIN_SOURCES_URL` constant to point to this file and to remove the mocks we currently have in the e2e tests for plugin sources.

**Comment by nglgzz** [comment]
Good point, will check that

**Review by jk05 — APPROVED** [review]

**Comment by nglgzz** [comment]
I couldn't find anything official specific to the raw.githubusercontent.com endpoint, and the little information I found was conflicting, so it's probably best to create an endpoint like you suggested @huboneo.

**Pull request closed without merging**
